var data=[
			{
	            "% RETI Adoption": 98.36,
	            "Total Dev Escape [%]": 10,
	            "Total Test Escape [TTE %]": 65,
	            "URC MTTR": 37.07,
	            "CFD MTTR - Average Outstanding": 24.57,
	            "SS MTTR - Average Outstanding": 6.01,
	            "TS MTTR - Average Outstanding": 6.01,
	            "RG": 118,
	            "URC": 69,
	            "S123 Backlog": 1158,
	            "CFD Backlog": 147,
	            "PSIRT - Critical": 1,
	            "PSIRT - High": 1,
	            "S12 Autons Backlog": 9,
	            "S3 Autons Backlog": 136,
	            "% RETI Adoption_trend": "Up",
	            "Total Dev Escape [%]_trend": "Up",
	            "Total Test Escape [TTE %]_trend": "Up",
	            "URC MTTR_trend": "Up",
	            "CFD MTTR - Average Outstanding_trend": "Up",
	            "SS MTTR - Average Outstanding_trend": "Up",
	            "TS MTTR - Average Outstanding_trend": "Up",
	            "RG_trend": "Up",
	            "URC_trend": "Down",
	            "S123 Backlog_trend": "Up",
	            "CFD Backlog_trend": "Up",
	            "PSIRT - Critical_trend": "Down",
	            "PSIRT - High_trend": "Down",
	            "S12 Autons Backlog_trend": "Up",
	            "S3 Autons Backlog_trend": "Down",
	            "ViewName": "1661 RelView"
	        },
			{
	            "% RETI Adoption": 97.36,
	            "Total Dev Escape [%]": 10,
	            "Total Test Escape [TTE %]": 65,
	            "URC MTTR": 37.07,
	            "CFD MTTR - Average Outstanding": 24.57,
	            "SS MTTR - Average Outstanding": 6.01,
	            "TS MTTR - Average Outstanding": 6.01,
	            "RG": 118,
	            "URC": 69,
	            "S123 Backlog": 1158,
	            "CFD Backlog": 147,
	            "PSIRT - Critical": 1,
	            "PSIRT - High": 1,
	            "S12 Autons Backlog": 9,
	            "S3 Autons Backlog": 136,
	            "% RETI Adoption_trend": "Up",
	            "Total Dev Escape [%]_trend": "Up",
	            "Total Test Escape [TTE %]_trend": "Up",
	            "URC MTTR_trend": "Up",
	            "CFD MTTR - Average Outstanding_trend": "Up",
	            "SS MTTR - Average Outstanding_trend": "Up",
	            "TS MTTR - Average Outstanding_trend": "Up",
	            "RG_trend": "Up",
	            "URC_trend": "Down",
	            "S123 Backlog_trend": "Up",
	            "CFD Backlog_trend": "Up",
	            "PSIRT - Critical_trend": "Down",
	            "PSIRT - High_trend": "Down",
	            "S12 Autons Backlog_trend": "Up",
	            "S3 Autons Backlog_trend": "Down",
	            "ViewName": "Sri"
	        },
			{
	            "% RETI Adoption": 90.36,
	            "Total Dev Escape [%]": 10,
	            "Total Test Escape [TTE %]": 65,
	            "URC MTTR": 37.07,
	            "CFD MTTR - Average Outstanding": 24.57,
	            "SS MTTR - Average Outstanding": 6.01,
	            "TS MTTR - Average Outstanding": 6.01,
	            "RG": 118,
	            "URC": 69,
	            "S123 Backlog": 1158,
	            "CFD Backlog": 147,
	            "PSIRT - Critical": 1,
	            "PSIRT - High": 1,
	            "S12 Autons Backlog": 9,
	            "S3 Autons Backlog": 136,
	            "% RETI Adoption_trend": "Up",
	            "Total Dev Escape [%]_trend": "Up",
	            "Total Test Escape [TTE %]_trend": "Up",
	            "URC MTTR_trend": "Up",
	            "CFD MTTR - Average Outstanding_trend": "Up",
	            "SS MTTR - Average Outstanding_trend": "Up",
	            "TS MTTR - Average Outstanding_trend": "Up",
	            "RG_trend": "Up",
	            "URC_trend": "Down",
	            "S123 Backlog_trend": "Up",
	            "CFD Backlog_trend": "Up",
	            "PSIRT - Critical_trend": "Down",
	            "PSIRT - High_trend": "Down",
	            "S12 Autons Backlog_trend": "Up",
	            "S3 Autons Backlog_trend": "Down",
	            "ViewName": "Sri1"
	        }
			
];